// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWfq_Nf7ahQoIVflD0CqS8_GWdO-JszjI',
    appId: '1:313330203623:web:52ac0425474dbb533d1b42',
    messagingSenderId: '313330203623',
    projectId: 'ifree-ab709',
    authDomain: 'ifree-ab709.firebaseapp.com',
    storageBucket: 'ifree-ab709.firebasestorage.app',
    measurementId: 'G-67J9ZBB2XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtYmiqxl2y-5bSCAHHrINMyr5LLcQzDnY',
    appId: '1:313330203623:android:13c45e8ed434fbf03d1b42',
    messagingSenderId: '313330203623',
    projectId: 'ifree-ab709',
    storageBucket: 'ifree-ab709.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUbIrEhQwwBYhVJFeR2N4HxG7w0pTvu0w',
    appId: '1:313330203623:ios:cae9e80dac0cbd9c3d1b42',
    messagingSenderId: '313330203623',
    projectId: 'ifree-ab709',
    storageBucket: 'ifree-ab709.firebasestorage.app',
    iosClientId: '313330203623-avsmp4ma5rcp5ks9sq1rprt76ron9ula.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifreeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUbIrEhQwwBYhVJFeR2N4HxG7w0pTvu0w',
    appId: '1:313330203623:ios:cae9e80dac0cbd9c3d1b42',
    messagingSenderId: '313330203623',
    projectId: 'ifree-ab709',
    storageBucket: 'ifree-ab709.firebasestorage.app',
    iosClientId: '313330203623-avsmp4ma5rcp5ks9sq1rprt76ron9ula.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifreeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWrbP4YPs5e0mWGmdfZ_QDvDqXl379CBc',
    appId: '1:313330203623:web:a395dd9bc0c589663d1b42',
    messagingSenderId: '313330203623',
    projectId: 'ifree-ab709',
    authDomain: 'ifree-ab709.firebaseapp.com',
    storageBucket: 'ifree-ab709.firebasestorage.app',
    measurementId: 'G-DFW2F3FC8Z',
  );
}
